/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/accounts': RouteRecordInfo<
      '/accounts',
      '/accounts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/audit': RouteRecordInfo<
      '/audit',
      '/audit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/billing': RouteRecordInfo<
      '/billing',
      '/billing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/compute-access': RouteRecordInfo<
      '/compute-access',
      '/compute-access',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/enterprise': RouteRecordInfo<
      '/enterprise',
      '/enterprise',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/models': RouteRecordInfo<
      '/models',
      '/models',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/orders': RouteRecordInfo<
      '/orders',
      '/orders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/packages': RouteRecordInfo<
      '/packages',
      '/packages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile/': RouteRecordInfo<
      '/profile/',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/subscribed-services': RouteRecordInfo<
      '/subscribed-services',
      '/subscribed-services',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/usage': RouteRecordInfo<
      '/usage',
      '/usage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user-accounts': RouteRecordInfo<
      '/user-accounts',
      '/user-accounts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/wallet': RouteRecordInfo<
      '/wallet',
      '/wallet',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/views/accounts.vue': {
      routes:
        | '/accounts'
      views:
        | never
    }
    'src/views/audit.vue': {
      routes:
        | '/audit'
      views:
        | never
    }
    'src/views/billing.vue': {
      routes:
        | '/billing'
      views:
        | never
    }
    'src/views/compute-access.vue': {
      routes:
        | '/compute-access'
      views:
        | never
    }
    'src/views/dashboard.vue': {
      routes:
        | '/dashboard'
      views:
        | never
    }
    'src/views/enterprise.vue': {
      routes:
        | '/enterprise'
      views:
        | never
    }
    'src/views/models.vue': {
      routes:
        | '/models'
      views:
        | never
    }
    'src/views/orders.vue': {
      routes:
        | '/orders'
      views:
        | never
    }
    'src/views/packages.vue': {
      routes:
        | '/packages'
      views:
        | never
    }
    'src/views/profile/index.vue': {
      routes:
        | '/profile/'
      views:
        | never
    }
    'src/views/subscribed-services.vue': {
      routes:
        | '/subscribed-services'
      views:
        | never
    }
    'src/views/usage.vue': {
      routes:
        | '/usage'
      views:
        | never
    }
    'src/views/user-accounts.vue': {
      routes:
        | '/user-accounts'
      views:
        | never
    }
    'src/views/wallet.vue': {
      routes:
        | '/wallet'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
